# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_author_name', models.CharField(max_length=50)),
                ('second_author_name', models.CharField(max_length=50)),
                ('third_author_name', models.CharField(max_length=50)),
                ('journal', models.CharField(max_length=50)),
                ('year_of_publication', models.IntegerField(default=2017)),
                ('volume', models.IntegerField(default=1)),
                ('issue', models.IntegerField(default=1)),
                ('pp', models.CharField(max_length=15)),
            ],
        ),
    ]
