# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
