# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_publication_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
