# Generated by Django 3.2.13 on 2022-06-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_publication_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=10)),
                ('last_name', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='publication',
            name='first_author_name',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='second_author_name',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='third_author_name',
        ),
        migrations.AddField(
            model_name='publication',
            name='authors',
            field=models.ManyToManyField(to='app.Author'),
        ),
    ]
