# Generated by Django 3.2.13 on 2022-06-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220615_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_id',
            field=models.CharField(default='', max_length=10),
        ),
    ]
