# Generated by Django 3.2.13 on 2022-06-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_author_author_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='author',
            name='highest_qualification',
            field=models.CharField(default='', max_length=10),
        ),
    ]
