# Generated by Django 3.2.13 on 2022-06-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=20)),
                ('date', models.DateTimeField(max_length=20)),
                ('time_in', models.DateTimeField(max_length=20)),
                ('time_out', models.DateTimeField(max_length=20)),
            ],
        ),
    ]
