# Generated by Django 3.2.13 on 2022-06-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='time_out',
            field=models.DateTimeField(max_length=20, null=True),
        ),
    ]
