# Generated by Django 3.2.13 on 2022-06-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='hours',
            field=models.FloatField(default=0, null=True),
        ),
    ]
